# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_qqsegment', [dirname(__file__)])
        except ImportError:
            import _qqsegment
            return _qqsegment
        if fp is not None:
            try:
                _mod = imp.load_module('_qqsegment', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _qqsegment = swig_import_helper()
    del swig_import_helper
else:
    import _qqsegment
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _qqsegment.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _qqsegment.SwigPyIterator_value(self)
    def incr(self, n=1): return _qqsegment.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _qqsegment.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _qqsegment.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _qqsegment.SwigPyIterator_equal(self, *args)
    def copy(self): return _qqsegment.SwigPyIterator_copy(self)
    def next(self): return _qqsegment.SwigPyIterator_next(self)
    def __next__(self): return _qqsegment.SwigPyIterator___next__(self)
    def previous(self): return _qqsegment.SwigPyIterator_previous(self)
    def advance(self, *args): return _qqsegment.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _qqsegment.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _qqsegment.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _qqsegment.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _qqsegment.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _qqsegment.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _qqsegment.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _qqsegment.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _qqsegment.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _qqsegment.StringVector___nonzero__(self)
    def __bool__(self): return _qqsegment.StringVector___bool__(self)
    def __len__(self): return _qqsegment.StringVector___len__(self)
    def pop(self): return _qqsegment.StringVector_pop(self)
    def __getslice__(self, *args): return _qqsegment.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _qqsegment.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _qqsegment.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _qqsegment.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _qqsegment.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _qqsegment.StringVector___setitem__(self, *args)
    def append(self, *args): return _qqsegment.StringVector_append(self, *args)
    def empty(self): return _qqsegment.StringVector_empty(self)
    def size(self): return _qqsegment.StringVector_size(self)
    def clear(self): return _qqsegment.StringVector_clear(self)
    def swap(self, *args): return _qqsegment.StringVector_swap(self, *args)
    def get_allocator(self): return _qqsegment.StringVector_get_allocator(self)
    def begin(self): return _qqsegment.StringVector_begin(self)
    def end(self): return _qqsegment.StringVector_end(self)
    def rbegin(self): return _qqsegment.StringVector_rbegin(self)
    def rend(self): return _qqsegment.StringVector_rend(self)
    def pop_back(self): return _qqsegment.StringVector_pop_back(self)
    def erase(self, *args): return _qqsegment.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _qqsegment.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _qqsegment.StringVector_push_back(self, *args)
    def front(self): return _qqsegment.StringVector_front(self)
    def back(self): return _qqsegment.StringVector_back(self)
    def assign(self, *args): return _qqsegment.StringVector_assign(self, *args)
    def resize(self, *args): return _qqsegment.StringVector_resize(self, *args)
    def insert(self, *args): return _qqsegment.StringVector_insert(self, *args)
    def reserve(self, *args): return _qqsegment.StringVector_reserve(self, *args)
    def capacity(self): return _qqsegment.StringVector_capacity(self)
    __swig_destroy__ = _qqsegment.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _qqsegment.StringVector_swigregister
StringVector_swigregister(StringVector)

class QQSegmenter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, QQSegmenter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, QQSegmenter, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _qqsegment.new_QQSegmenter()
        try: self.this.append(this)
        except: self.this = this
    __swig_getmethods__["GetDefaultMode"] = lambda x: _qqsegment.QQSegmenter_GetDefaultMode
    if _newclass:GetDefaultMode = staticmethod(_qqsegment.QQSegmenter_GetDefaultMode)
    __swig_destroy__ = _qqsegment.delete_QQSegmenter
    __del__ = lambda self : None;
    def Init(self, *args): return _qqsegment.QQSegmenter_Init(self, *args)
    def Segment(self, *args): return _qqsegment.QQSegmenter_Segment(self, *args)
QQSegmenter_swigregister = _qqsegment.QQSegmenter_swigregister
QQSegmenter_swigregister(QQSegmenter)

def QQSegmenter_GetDefaultMode():
  return _qqsegment.QQSegmenter_GetDefaultMode()
QQSegmenter_GetDefaultMode = _qqsegment.QQSegmenter_GetDefaultMode

# This file is compatible with both classic and new-style classes.


